source "$HOME/.dotfiles/zsh/common.zsh"

case "$(uname -s)" in
  Linux)
    source "$HOME/.dotfiles/zsh/linux.zsh"

    if [[ -r /etc/os-release ]]; then
      source /etc/os-release

      case "$ID" in
        fedora)
          source "$HOME/.dotfiles/zsh/fedora.zsh"
          ;;
        cachyos)
          source "$HOME/.dotfiles/zsh/cachyos.zsh"
          ;;
        ubuntu)
          source "$HOME/.dotfiles/zsh/ubuntu.zsh"
          ;;
      esac
    fi
    ;;
esac

if [[ ${DOTFILES_MINERVA:-} == 1 ]]; then
  source "$HOME/.dotfiles/zsh/minerva.zsh"
fi

source "$HOME/.dotfiles/zsh/prompt.zsh"

if [[ -r "$HOME/.zshrc.local" ]]; then
  source "$HOME/.zshrc.local"
fi

true
